[package]
name = "define3"
version = "0.1.0"
authors = ["Jim Zhang <hyriodula@gmail.com>"]

[dependencies]
quick-xml = "0.10.0"
rusqlite = "0.13.0"
colored = "1.6.0"
textwrap = "0.9.0"
regex = "0.2.10"
getopts = "0.2.17"
nom = "3.2.1"
